/**
 * Static registry of the 3D models available in the model library.
 *
 * Each model file lives at apps/web/public/models/<file>, which Next.js
 * serves automatically at /models/<file> — no API route needed to fetch
 * the .glb itself. This registry is just the metadata (name, subject,
 * search terms) that drives the picker UI and the search bar; the actual
 * geometry is loaded client-side by <model-viewer> from the public path.
 *
 * `id` is what gets broadcast over the wire (ClassroomEvent's
 * `ActiveModel.modelId`) — every client resolves it back to a full Model3D
 * via `getModel()` rather than trusting anything about the model over the
 * network beyond its id.
 */

export type ModelSubject = 'Biology' | 'Astronomy' | 'Physics' | 'Chemistry' | 'Math';

export interface Model3D {
  id: string;
  name: string;
  /** Filename inside apps/web/public/models/ */
  file: string;
  subject: ModelSubject;
  /** Short line shown under the name in the picker tile. */
  description: string;
  /**
   * Attribution text for CC-licensed models, shown in a credits section.
   * Undefined for CC0 models, where no credit is legally required.
   */
  credit?: string;
}

export const MODELS_3D: Model3D[] = [
  {
    id: 'beating-heart',
    name: 'Beating Heart',
    file: 'beating-heart.glb',
    subject: 'Biology',
    description: 'Human heart, chambers and major vessels.',
  },
  {
    id: 'human-brain',
    name: 'Human Brain',
    file: 'human_brain.glb',
    subject: 'Biology',
    description: 'Lobes, hemispheres, and major surface structures.',
  },
  {
    id: 'skull',
    name: 'Human Skull',
    file: 'skull_downloadable.glb',
    subject: 'Biology',
    description: 'Cranial and facial bone structure.',
  },
  {
    id: 'nervous-system',
    name: 'Nervous System',
    file: 'nervous_system.glb',
    subject: 'Biology',
    description: 'Central and peripheral nervous system layout.',
  },
  {
    id: 'digestive-system',
    name: 'Digestive System',
    file: 'digestive_system.glb',
    subject: 'Biology',
    description: 'Full digestive tract',
  },
  {
    id: 'animal-cell',
    name: 'Animal Cell',
    file: 'animal_cell.glb',
    subject: 'Biology',
    description: 'Organelles inside a typical animal cell.',
  },
  {
    id: 'plant-cell',
    name: 'Plant Cell',
    file: 'plant_cell.glb',
    subject: 'Biology',
    description: 'Cell wall, chloroplasts, and other plant organelles.',
  },
  {
    id: 'chloroplast',
    name: 'Chloroplast',
    file: 'chloroplast.glb',
    subject: 'Biology',
    description: 'Internal structure of a chloroplast, site of photosynthesis.',
  },
  {
    id: 'bee-pollination',
    name: 'Bee Pollination',
    file: 'bug_pollination_by_bees.glb',
    subject: 'Biology',
    description: 'How bees transfer pollen between flowers.',
  },
  {
    id: 'solar-system',
    name: 'Solar System (Orrery)',
    file: 'solar_system_model_orrery.glb',
    subject: 'Astronomy',
    description: 'Sun and planets in relative orbital motion.',
  },
  {
    id: 'earth-core',
    name: "Earth's Core",
    file: 'earth_core_v2.glb',
    subject: 'Astronomy',
    description: "Cross-section of Earth's inner and outer core, mantle, and crust.",
  },
  {
    id: 'asteroid',
    name: 'Asteroid',
    file: 'asteroid.glb',
    subject: 'Astronomy',
    description: 'Irregular rocky asteroid surface detail.',
  },
  {
    id: 'satellite',
    name: 'Satellite',
    file: 'satelite.glb',
    subject: 'Astronomy',
    description: 'Orbital satellite structure and solar panels.',
  },
  {
    id: 'circumstellar-disk',
    name: 'Circumstellar Disk',
    file: 'circumstellar_disk.glb',
    subject: 'Astronomy',
    description: 'Disk of gas and dust orbiting a young star.',
  },
  {
    id: 'atom',
    name: 'Atom',
    file: 'atom.glb',
    subject: 'Physics',
    description: 'Nucleus and electron orbitals.',
  },
  {
    id: 'plasma',
    name: 'Plasma',
    file: 'evanescent_plasma.glb',
    subject: 'Physics',
    description: 'Ionized gas, the fourth state of matter.',
  },
  {
    id: 'solenoid-field',
    name: 'Magnetic Field of a Solenoid',
    file: 'magnetic_field_of_solenoid_by_yuyalyj.glb',
    subject: 'Physics',
    description: 'Field lines generated by a current-carrying coil.',
  },
  {
    id: 'periodic-table',
    name: 'Periodic Table',
    file: 'periodic_table.glb',
    subject: 'Chemistry',
    description: 'Full periodic table of elements, in 3D.',
  },
  {
    id: 'pythagorean-theorem',
    name: 'Pythagorean Theorem',
    file: 'pythagorean_theorem.glb',
    subject: 'Math',
    description: 'Visual proof of a² + b² = c² on a right triangle.',
  },
];

export function getModel(id: string): Model3D | undefined {
  return MODELS_3D.find((m) => m.id === id);
}

export function modelFileUrl(model: Model3D): string {
  return `/models/${model.file}`;
}

/** Simple case-insensitive match against name, subject, and description. */
export function searchModels(query: string): Model3D[] {
  const q = query.trim().toLowerCase();
  if (!q) return MODELS_3D;
  return MODELS_3D.filter(
    (m) =>
      m.name.toLowerCase().includes(q) ||
      m.subject.toLowerCase().includes(q) ||
      m.description.toLowerCase().includes(q),
  );
}